#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${ENV_FILE:-$PROJECT_DIR/.env}"

GITHUB_REPO="${GITHUB_REPO:-RAdu2005/cupstream}"
AUTH_SVC_BIN="${AUTH_SVC_BIN:-}"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

prompt() {
	local var="$1"
	local msg="$2"
	local default="${3:-}"
	local val

	if [ -n "${!var:-}" ]; then
		return 0
	fi

	if [ -n "$default" ]; then
		read -rp "$msg [$default]: " val
		val="${val:-$default}"
	else
		read -rp "$msg: " val
	fi

	if [ -z "$val" ]; then
		echo "Error: $var is required." >&2
		exit 1
	fi

	declare -g "$var=$val"
}

prompt_secret() {
	local var="$1"
	local msg="$2"
	local val

	if [ -n "${!var:-}" ]; then
		return 0
	fi

	read -rsp "$msg: " val
	echo >&2

	if [ -z "$val" ]; then
		echo "Error: $var is required." >&2
		exit 1
	fi

	declare -g "$var=$val"
}

hash_password() {
	local pw="$1"
	local bin="$AUTH_SVC_BIN"

	if [ -z "$bin" ] || [ ! -x "$bin" ]; then
		# Try to find auth-svc in PATH or project dir
		if command -v auth-svc >/dev/null 2>&1; then
			bin="$(command -v auth-svc)"
		elif [ -x "$PROJECT_DIR/auth-svc/auth-svc" ]; then
			bin="$PROJECT_DIR/auth-svc/auth-svc"
		elif [ -x "$PROJECT_DIR/auth-svc" ]; then
			bin="$PROJECT_DIR/auth-svc"
		fi
	fi

	if [ -n "$bin" ] && [ -x "$bin" ]; then
		"$bin" hash "$pw"
		return 0
	fi

	# Download latest release binary temporarily to run hash
	echo "Downloading auth-svc release binary to generate hash..." >&2
	local tmpdir
	tmpdir="$(mktemp -d)"
	trap 'rm -rf "$tmpdir"' RETURN

	local arch="amd64"
	[ "$(uname -m)" = "aarch64" ] && arch="arm64"

	local url="https://github.com/$GITHUB_REPO/releases/latest/download/auth-svc-linux-${arch}"
	local tmpbin="$tmpdir/auth-svc"

	if ! curl -fsSL -o "$tmpbin" "$url"; then
		echo "Failed to download auth-svc binary. Please build it locally or set AUTH_SVC_BIN." >&2
		exit 1
	fi

	chmod +x "$tmpbin"
	"$tmpbin" hash "$pw"
}

# ------------------------------------------------------------------
# Prompts
# ------------------------------------------------------------------

if [ -t 0 ]; then
	echo "=== auth-svc environment setup ===" >&2
	echo "Press Enter to accept defaults where shown." >&2
	echo
fi

prompt DOMAIN "Public domain (e.g. cup.larp.love)"
prompt MEDIAMTX_DOMAIN "MediaMTX direct domain (e.g. mediamtx.cup.larp.love)" "mediamtx.${DOMAIN}"
prompt_secret ADMIN_PASSWORD "Admin password"
prompt_secret OBS_PASSWORD "OBS publish password"

# ------------------------------------------------------------------
# Generation
# ------------------------------------------------------------------

JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
PASSWORD_HASH="${PASSWORD_HASH:-$(hash_password "$ADMIN_PASSWORD")}"
MEDIAMTX_PUBLISH_HASH="${MEDIAMTX_PUBLISH_HASH:-$(hash_password "$OBS_PASSWORD")}"

# ------------------------------------------------------------------
# Write
# ------------------------------------------------------------------

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date -Iseconds)
DOMAIN=${DOMAIN}
MEDIAMTX_DOMAIN=${MEDIAMTX_DOMAIN}
PASSWORD_HASH=${PASSWORD_HASH}
JWT_SECRET=${JWT_SECRET}
MEDIAMTX_API=http://127.0.0.1:9997
MEDIAMTX_WEBRTC=http://127.0.0.1:8889
MEDIAMTX_PUBLISH_USER=obs
MEDIAMTX_PUBLISH_HASH=${MEDIAMTX_PUBLISH_HASH}
MEDIAMTX_AUTH_ADDR=127.0.0.1:9998
PORT=443
TLS=yes
CERT_DIR=/var/lib/auth-svc/certs
EOF

echo "Wrote $ENV_FILE" >&2
echo "Review it, then run scripts/install.sh to deploy." >&2
